site_name: Marco de trabajo con GitOps
theme:
  name: material
  locale: es
  language: es
extra_css:
  - css/mikroways.css
plugins:
  - glightbox
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
nav:
  - index.md
  - Patrones y antipatrones:
    - patterns/index.md
    - ArgoCD:
      - patterns/argocd/index.md
      - patterns/argocd/ui.md
      - patterns/argocd/acceso-de-usuarios.md
      - patterns/argocd/versionado-valores.md
    - Helm:
      - patterns/helm/index.md
      - patterns/helm/chart-vs-charts.md
      - patterns/helm/schema-migrations.md
      - patterns/helm/requirements.md
    - patterns/secrets/index.md
    - patterns/environment/index.md
  - El marco de trabajo:
    - framework/index.md
    - framework/prerequisites.md
    - framework/git-repositories.md
    - framework/workflow.md
